#include "cmds/init.hpp"

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

#include "core/exe_path.hpp"
#include "core/exit_codes.hpp"

namespace mtk::cmds::init {

namespace {

// Format a path for inclusion in a shell single-quoted string (the bash
// hook script). Escapes embedded single quotes via the classic
// `'\''` trick.
std::string shell_single_quote(const std::filesystem::path& p) {
    const auto s = p.string();
    std::string out;
    out.reserve(s.size() + 2);
    out += '\'';
    for (char c : s) {
        if (c == '\'') out += "'\\''";
        else out += c;
    }
    out += '\'';
    return out;
}

// Format a path for inclusion in a JSON string value (escapes \ and ").
std::string json_escape(const std::filesystem::path& p) {
    const auto s = p.string();
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
        switch (c) {
            case '\\': out += "\\\\"; break;
            case '"':  out += "\\\""; break;
            default:   out += c; break;
        }
    }
    return out;
}

int run_init_claude() {
#if defined(_WIN32)
    std::cerr
        << "mtk init claude: not supported on Windows native.\n"
        << "\n"
        << "The Claude Code hook is a bash script that calls `jq` to\n"
        << "rewrite the PreToolUse JSON payload. cmd.exe / PowerShell\n"
        << "can't run it. Two paths forward:\n"
        << "\n"
        << "  1. Install + use mtk inside WSL2 — the Linux build runs\n"
        << "     natively and the bash hook works as-is.\n"
        << "  2. Use MSYS2 / Git Bash — has both bash and jq; the hook\n"
        << "     installs into your Windows user's ~/.claude/hooks/\n"
        << "     and Claude Code picks it up.\n"
        << "\n"
        << "The Copilot integration (`mtk init copilot`) is JSON-only\n"
        << "and works on Windows native — try that one if you're using\n"
        << "GitHub Copilot.\n";
    return mtk::core::exit_codes::kUsage;
#else
    const char* home = std::getenv("HOME");
    if (!home) {
        std::cerr << "mtk init: $HOME not set\n";
        return mtk::core::exit_codes::kUsage;
    }
    std::filesystem::path claude_dir = std::filesystem::path(home) / ".claude";
    std::filesystem::path hooks_dir = claude_dir / "hooks";
    std::filesystem::path hook_script = hooks_dir / "mtk-rewrite.sh";

    std::error_code ec;
    std::filesystem::create_directories(hooks_dir, ec);
    if (ec) {
        std::cerr << "mtk init: failed to create " << hooks_dir << ": "
                  << ec.message() << '\n';
        return mtk::core::exit_codes::kNotFound;
    }

    auto bin = mtk::core::executable_path();
    if (bin.empty()) {
        std::cerr << "mtk init: could not resolve own binary path; "
                     "the generated hook script will use bare 'mtk' "
                     "(requires PATH).\n";
    }
    std::string mtk_invoc = bin.empty() ? std::string{"mtk"}
                                        : shell_single_quote(bin);

    std::ostringstream body;
    body << "#!/usr/bin/env bash\n"
         << "# mtk-rewrite.sh — Claude Code PreToolUse hook (Bash tool only).\n"
         << "# Generated by `mtk init claude`. Reads tool input JSON from\n"
         << "# stdin, rewrites Bash commands through mtk, writes modified\n"
         << "# JSON to stdout. Requires `jq`. mtk binary is referenced by\n"
         << "# absolute path so no PATH setup is needed.\n"
         << "set -euo pipefail\n"
         << "\n"
         << "MTK=" << mtk_invoc << "\n"
         << "\n"
         << "input=$(cat)\n"
         << "tool_name=$(printf '%s' \"$input\" | jq -r '.tool_name // empty')\n"
         << "if [[ \"$tool_name\" != \"Bash\" ]]; then\n"
         << "    printf '%s' \"$input\"\n"
         << "    exit 0\n"
         << "fi\n"
         << "\n"
         << "cmd=$(printf '%s' \"$input\" | jq -r '.tool_input.command // empty')\n"
         << "if [[ -z \"$cmd\" ]]; then\n"
         << "    printf '%s' \"$input\"\n"
         << "    exit 0\n"
         << "fi\n"
         << "\n"
         << "# mtk rewrite emits either \"mtk <cmd>\" (wrap) or \"<cmd>\" (passthrough).\n"
         << "rewritten=$(printf '%s' \"$cmd\" | xargs -0 -I{} \"$MTK\" rewrite {} \\\n"
         << "            2>/dev/null || printf '%s' \"$cmd\")\n"
         << "printf '%s' \"$input\" | jq --arg c \"$rewritten\" '.tool_input.command = $c'\n";

    std::ofstream f(hook_script);
    if (!f) {
        std::cerr << "mtk init: failed to write " << hook_script << '\n';
        return mtk::core::exit_codes::kNotFound;
    }
    f << body.str();
    f.close();
    std::filesystem::permissions(hook_script,
        std::filesystem::perms::owner_read |
        std::filesystem::perms::owner_write |
        std::filesystem::perms::owner_exec |
        std::filesystem::perms::group_read |
        std::filesystem::perms::group_exec |
        std::filesystem::perms::others_read |
        std::filesystem::perms::others_exec,
        std::filesystem::perm_options::replace, ec);

    std::cout << "Wrote " << hook_script << " (chmod 755)\n"
              << "\n"
              << "Manual step — add to ~/.claude/settings.json (under \"hooks\"):\n"
              << "\n"
              << "  \"PreToolUse\": [\n"
              << "    {\n"
              << "      \"matcher\": \"Bash\",\n"
              << "      \"hooks\": [\n"
              << "        {\n"
              << "          \"type\": \"command\",\n"
              << "          \"command\": \"" << hook_script.string() << "\"\n"
              << "        }\n"
              << "      ]\n"
              << "    }\n"
              << "  ]\n"
              << "\n"
              << "Requires `jq`. mtk binary path is baked into the hook —\n"
              << "no PATH setup needed. Re-run `mtk init claude` if you\n"
              << "move the binary.\n";
    return 0;
#endif
}

int run_init_copilot() {
    std::filesystem::path github_dir = std::filesystem::current_path() / ".github";
    std::filesystem::path hooks_dir = github_dir / "hooks";
    std::filesystem::path hook_json = hooks_dir / "mtk-rewrite.json";
    std::filesystem::path instructions = github_dir / "copilot-instructions.md";

    std::error_code ec;
    std::filesystem::create_directories(hooks_dir, ec);
    if (ec) {
        std::cerr << "mtk init copilot: failed to create " << hooks_dir
                  << ": " << ec.message() << '\n';
        return mtk::core::exit_codes::kNotFound;
    }

    // Dual-format hook config: PreToolUse for VS Code Copilot Chat,
    // preToolUse for Copilot CLI. Both call `mtk hook copilot` which
    // detects the input shape and rewrites accordingly. Use the absolute
    // path of the current mtk binary so build-only users don't need PATH.
    auto bin = mtk::core::executable_path();
    if (bin.empty()) {
        std::cerr << "mtk init copilot: could not resolve own binary "
                     "path; the generated hook config will use bare "
                     "'mtk' (requires PATH).\n";
    }

    std::ostringstream hook_json_stream;
    hook_json_stream
        << "{\n"
        << "  \"version\": 1,\n"
        << "  \"hooks\": {\n"
        << "    \"PreToolUse\": [\n"
        << "      {\n"
        << "        \"type\": \"command\",\n"
        << "        \"command\": " << (bin.empty() ? "\"mtk hook copilot\""
                                                   : ("\"" + json_escape(bin) + " hook copilot\""))
        << ",\n"
        << "        \"cwd\": \".\",\n"
        << "        \"timeout\": 5\n"
        << "      }\n"
        << "    ],\n"
        << "    \"preToolUse\": [\n"
        << "      {\n"
        << "        \"type\": \"command\",\n"
        << "        \"bash\": " << (bin.empty() ? "\"mtk hook copilot\""
                                                : ("\"" + json_escape(bin) + " hook copilot\""))
        << ",\n"
        << "        \"powershell\": " << (bin.empty() ? "\"mtk hook copilot\""
                                                      : ("\"" + json_escape(bin) + " hook copilot\""))
        << ",\n"
        << "        \"cwd\": \".\",\n"
        << "        \"timeoutSec\": 5\n"
        << "      }\n"
        << "    ]\n"
        << "  }\n"
        << "}\n";
    const std::string kHookJson = hook_json_stream.str();

    constexpr const char* kInstructionsBlock = R"(<!-- mtk-instructions v1 -->
# mtk — Token-Optimized CLI

**mtk** is a CLI proxy that filters and compresses shell command output,
reducing tokens spent on tool results.

## Rule

When a shell command would benefit from filtering, prefix it with `mtk`:

```bash
# Instead of:              Use:
git status                 mtk git status
git log -10                mtk git log -10
git diff                   mtk git diff
ls /some/path              mtk ls /some/path
grep "pattern" src/        mtk grep "pattern" src/
```

The hook at `.github/hooks/mtk-rewrite.json` does this automatically
for known filters. The instructions above bias the model toward emitting
already-prefixed commands so the hook has less to rewrite.

## Meta-commands

```bash
mtk explain <cmd>     # Show which filter would match (dry-run)
mtk trusted           # List trusted project-filter paths
```
<!-- /mtk-instructions -->
)";

    {
        std::ofstream f(hook_json);
        if (!f) {
            std::cerr << "mtk init copilot: failed to write " << hook_json << '\n';
            return mtk::core::exit_codes::kNotFound;
        }
        f << kHookJson;
    }

    // For the instructions file: upsert (don't clobber existing user content).
    // If the file exists and already has our marker block, replace it;
    // otherwise append.
    std::string existing;
    if (std::ifstream in(instructions); in) {
        std::ostringstream ss; ss << in.rdbuf();
        existing = ss.str();
    }
    auto start_marker = std::string("<!-- mtk-instructions");
    auto end_marker = std::string("<!-- /mtk-instructions -->");
    auto block_start = existing.find(start_marker);
    auto block_end = (block_start != std::string::npos)
        ? existing.find(end_marker, block_start) : std::string::npos;
    std::string updated;
    if (block_start != std::string::npos && block_end != std::string::npos) {
        updated = existing.substr(0, block_start);
        updated += kInstructionsBlock;
        updated += existing.substr(block_end + end_marker.size());
    } else {
        updated = existing;
        if (!updated.empty() && updated.back() != '\n') updated += '\n';
        if (!updated.empty()) updated += '\n';
        updated += kInstructionsBlock;
    }
    {
        std::ofstream f(instructions);
        if (!f) {
            std::cerr << "mtk init copilot: failed to write " << instructions << '\n';
            return mtk::core::exit_codes::kNotFound;
        }
        f << updated;
    }

    std::cout << "Wrote " << hook_json << "\n"
              << "Wrote " << instructions
              << " (upserted mtk-instructions block)\n"
              << "\n"
              << "Restart your IDE or Copilot CLI session to activate.\n"
              << "\n"
              << "Notes:\n"
              << "  - Project-scoped — each repo needs its own `mtk init copilot`.\n"
              << "  - The mtk binary path is baked into the hook (no PATH needed).\n"
              << "    Re-run `mtk init copilot` if you move the binary.\n"
              << "  - Native subcommand (no jq required, unlike Claude).\n";
    return 0;
}

}  // namespace

int run_init(const std::vector<std::string>& argv) {
    if (argv.empty()) {
        std::cout
            << "mtk init <agent>\n"
            << "\n"
            << "Agents:\n"
            << "  claude    — Claude Code (claude.ai/code) — IMPLEMENTED\n"
            << "  copilot   — GitHub Copilot (VS Code + CLI) — IMPLEMENTED\n"
            << "  gemini    — Gemini CLI — TODO\n"
            << "  codex     — OpenAI Codex CLI — TODO\n"
            << "  cursor    — Cursor IDE — TODO\n"
            << "\n"
            << "Examples:\n"
            << "  mtk init claude     # per-user hook in ~/.claude/hooks/\n"
            << "  mtk init copilot    # per-project hook in .github/hooks/\n";
        return 0;
    }
    const auto& agent = argv[0];
    if (agent == "claude") return run_init_claude();
    if (agent == "copilot") return run_init_copilot();
    std::cerr << "mtk init: agent '" << agent
              << "' not yet supported. Run `mtk init` for the list.\n";
    return mtk::core::exit_codes::kUsage;
}

}  // namespace mtk::cmds::init
